#!/usr/bin/env python3
"""Generate the validator rule fixtures (synthetic palette and flats only; no EA data).

Layout (DESIGN §5.5: "Fixture PNGs with expected rule IDs ... both test suites use them")::

    <out>/game/palettes.flx, <out>/game/shapes.vga   synthetic game data (the provider)
    <out>/<case>/<SSSS_FF>.png                      one file per case
    <out>/expected.txt                              "<case>/<file> <RULE|OK> <severity>"

Deterministic: running it twice gives identical bytes (pytest checks the committed copy).
usage: make_rule_fixtures.py [OUT]   (default: tests/data/rules)
"""

import os
import sys


HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
sys.path.insert(0, HERE)

import synth  # noqa: E402
from u7hires import io, pngio, rules  # noqa: E402
from u7hires.hashing import crc32  # noqa: E402

S = 6


def build(out: str) -> list[tuple[str, str, str]]:
    os.makedirs(os.path.join(out, "game"), exist_ok=True)
    p6 = synth.synth_palette6()
    with open(os.path.join(out, "game", "palettes.flx"), "wb") as f:
        f.write(io.build_flex([synth.pal6_bytes(p6)]))
    with open(os.path.join(out, "game", "shapes.vga"), "wb") as f:
        f.write(io.build_flex(synth.shapes_entries()))
    pal8 = io.palette8_from_6bit(p6 & 0xFF)
    shapes = synth.synth_shapes()

    def nn(s, f):
        return rules.nn_upscale(shapes.flat(s, f), S)

    def guard(s, f):
        return [("Exult-Src-CRC32", f"{crc32(shapes.flat(s, f).tobytes()):08x}")]

    cases = []

    def put(case, name, data, rule, sev):
        d = os.path.join(out, case)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, name), "wb") as fh:
            fh.write(data)
        cases.append((f"{case}/{name}", rule, sev))

    put("ok", "0001_02.png", pngio.encode_indexed(nn(1, 2), pal8, guard(1, 2)), "OK", "-")
    put("ok_unguarded", "0001_03.png", pngio.encode_indexed(nn(1, 3), pal8), "OK", "-")
    put("n1_name", "tile1.png", pngio.encode_indexed(nn(1, 0), pal8), "N1", "reject")
    put("n1_frame", "0001_40.png", pngio.encode_indexed(nn(1, 8), pal8), "N1", "reject")
    put("n1_shape", "0020_00.png", pngio.encode_indexed(nn(1, 0), pal8), "N1", "reject")
    put("n1_rle", f"{synth.RLE_SHAPE:04d}_00.png", pngio.encode_indexed(nn(1, 0), pal8), "N1", "reject")
    put("n1_missing", "0012_05.png", pngio.encode_indexed(nn(12, 1), pal8), "N1", "reject")
    rgb = pal8[nn(1, 4)]
    raw = b"".join(b"\0" + row.tobytes() for row in rgb)
    put("f1_rgb", "0001_04.png", pngio.build_png(48, 48, 8, 2, raw), "F1", "reject")
    t = nn(1, 5)
    bad_pal = pal8.copy()
    used = int(t[0, 0])
    bad_pal[used] = (bad_pal[used].astype(int) + 9) % 256
    put("f2_plte", "0001_05.png", pngio.encode_indexed(t, bad_pal), "F2", "reject")
    t = nn(1, 6)
    put("f2_short", "0001_06.png", pngio.encode_indexed(t, pal8[: int(t.max())]), "F2", "reject")
    put("f3_size", "0001_07.png", pngio.encode_indexed(nn(1, 7)[:40, :40], pal8), "F3", "reject")
    put("f4_trns", "0001_08.png", pngio.encode_indexed(nn(1, 8), pal8, trns=b"\0"), "F4", "warning")
    t = nn(1, 9).copy()
    t[10, 10] = 0xFF
    put("p0_ff", "0001_09.png", pngio.encode_indexed(t, pal8), "P0", "reject")
    # shape 2 has E0-E7 glints; put a block of E3 pixels far from any cycling parent
    src = shapes.flat(2, 0)
    far = [(y, x) for y in range(8) for x in range(8)
           if not (rules.CYCLE_ID[src[max(0, y - 1):y + 2, max(0, x - 1):x + 2]] == 0).any()]
    py, px = far[0]
    t = nn(2, 0).copy()
    t[py * S:py * S + 4, px * S:px * S + 4] = 0xE3          # 16 px = 0.69 % > 0.5 %
    put("p4_reject", "0002_00.png", pngio.encode_indexed(t, pal8), "P4", "reject")
    t = nn(2, 0).copy()
    t[py * S, px * S] = 0xE3                                  # 1 px: warning
    put("p4_warning", "0002_00.png", pngio.encode_indexed(t, pal8), "P4", "warning")
    put("g1_stale", "0001_10.png", pngio.encode_indexed(nn(1, 10), pal8, [("Exult-Src-CRC32", "00000000")]),
        "G1", "reject")
    put("g1_malformed", "0001_11.png", pngio.encode_indexed(nn(1, 11), pal8, [("Exult-Src-CRC32", "xyz")]),
        "G1", "reject")
    # offline P2: a whole block moved to another ramp (still a valid file for the engine)
    t = nn(1, 12).copy()
    other = 0x90 if rules.ramp_lut(rules.engine_ramps(p6 & 0xFF))[int(t[0, 0])] != \
        rules.ramp_lut(rules.engine_ramps(p6 & 0xFF))[0x90] else 0xA0
    t[:S, :S] = other
    put("p2_offline", "0001_12.png", pngio.encode_indexed(t, pal8, guard(1, 12)), "P2", "offline")
    lines = ["# <case>/<file> <expected primary rule or OK> <severity>; generated by make_rule_fixtures.py"]
    lines += [f"{c} {r} {s}" for c, r, s in cases]
    with open(os.path.join(out, "expected.txt"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    return cases


if __name__ == "__main__":
    build(sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "data", "rules"))
